set directory=$XDG_CACHE_HOME/vim,~/,/tmp
set backupdir=$XDG_CACHE_HOME/vim,~/,/tmp
set viminfo+=n$XDG_CACHE_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIM,$VIMRUNTIME
let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"

set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.config/vim/bundle/Vundle.vim
" alternatively, pass a path where Vundle should install plugins
call vundle#begin('~/.config/vim/bundle')

Plugin 'VundleVim/Vundle.vim'
" https://github.com/editorconfig/editorconfig-vim
Plugin 'editorconfig/editorconfig-vim'
" https://github.com/posva/vim-vue
Plugin 'posva/vim-vue'


call vundle#end()            " required
filetype plugin indent on    " required

" <Ctrl-l> redraws the screen and removes any search highlighting.
nnoremap <silent> <C-l> :nohl<CR><C-l>

:set expandtab
:set tabstop=4
:set shiftwidth=4
:set ignorecase
:set smartcase

" Custom colorscheme for vimdiff \o/
if &diff
    highlight DiffAdd    cterm=bold ctermfg=10 ctermbg=Blue gui=none guifg=bg guibg=Red
    highlight DiffDelete cterm=bold ctermfg=10  ctermbg=Red gui=none guifg=bg guibg=Red
    highlight DiffChange cterm=bold ctermfg=Black ctermbg=White gui=none guifg=bg guibg=Red
    highlight DiffText   cterm=bold ctermfg=White ctermbg=Magenta gui=none guifg=bg guibg=Red
endif

highlight ColorColumn ctermbg=magenta
call matchadd('ColorColumn', '\%81v', 100)

autocmd BufRead,BufNewFile   *.c,*.h,*.java,*.dts,*.dtsi set cin noexpandtab sw=8 ts=8
